#!/bin/sh
# script to display day as a dot

case $(date +%a) in
	*Sun*) echo "󰄯 󰄰 󰄰 󰄰 󰄰 󰄰 󰄰 " ;;
	*Mon*) echo "󰄯 󰄯 󰄰 󰄰 󰄰 󰄰 󰄰 " ;;
	*Tue*) echo "󰄯 󰄯 󰄯 󰄰 󰄰 󰄰 󰄰 " ;;
	*Wed*) echo "󰄯 󰄯 󰄯 󰄯 󰄰 󰄰 󰄰 " ;;
	*Thu*) echo "󰄯 󰄯 󰄯 󰄯 󰄯 󰄰 󰄰 " ;;
	*Fri*) echo "󰄯 󰄯 󰄯 󰄯 󰄯 󰄯 󰄰 " ;;
	*Sat*) echo "󰄯 󰄯 󰄯 󰄯 󰄯 󰄯 󰄯 " ;;
esac
